### ISSUE TITLE
please specify licensing

### ISSUE THREAD

**Issue by maltfield** [SergKolo/sergrep#10]
Hello,

Can you please specify a `LICENSE` file at the root of this repo, such as [this one for GPLv3](https://www.gnu.org/licenses/gpl-3.0.txt) so that users can use your code on other stack exchange sites?

I came across one of your answers on AskUbuntu, and I'd like to use some of your code, modify it, and post it to a similar question on Stack Exchange. Unfortunately, the licensing of the code in question is ambiguous in this repo.

Please explicitly set the license for the content of this repo to the GPL or similar permissive license so that the community can use, adapt, and publish your work on other stack exchange sites.

Thank you,
Michael

**Comment by SergKolo** [comment]
@kos0  @aboettger @yar-trach @ByteCommander @bvanrijn  So considering that you guys have contributed to this repository, do any of you have objections or suggestions on how to license this repo ? I typically license my stuff under MIT License, but if you want we can consider going GPLv3 or GPLv2 route to protect your individual contributions, too.

**Comment by nrth3rnlb** [comment]
CC0 :)

**Comment by ByteCommander** [comment]
I like MIT, but anything is fine with me, really. I don't claim ownership of any parts of the code, just contributed some minor fix in one of the scripts ;)

**Comment by SergKolo** [comment]
@aboettger  lol,  that'd be probably unfair to force everyone's contribution into public domain

**Comment by SergKolo** [comment]
Alright, so unless there's any further objections by Monday, 08/31/2020 ,  I'll go with MIT license for this one

**Comment by SergKolo** [comment]
@maltfield  

The repository is now licensed under  MIT.  I do appreciate the community interest in my works, and it always is a joy to see when my works are found to be useful. 

Feel free to use and distribute the code in this repository, modify as desired, and  most importantly - have fun !
